name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t ralphiko/dockerfile .

  publish_to_dockerhub:
    runs-on: ubuntu-latest
    needs: test_and_build
    if: github.ref == 'refs/tags/*'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Push Docker image
        run: docker push ralphiko/dockerfile