name: Docker Workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . -t ralphiko/dockerfile:latest
          docker run ralphiko/dockerfile:latest go test ./...  # Assuming this is how you run tests in your Go project
